db:
  host: '192.168.1.229'
  port: 3306
  user: 'dev'
  password: 'Awesome85**'
  name: 'report'

consumer:
  brokers: ['192.168.1.229:9092']
  topic: 'store.report.report'
  group_id: 'consumer.report.user'

health:
  port: ':8280'
  shutdown_endpoint: '/api/v1/consumer_report_user_health/shutdown'
  content_type: 'application/json'